services:
#    workflow.example:
#        class: WorkflowBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  workflow.processor:
    class: WorkflowBundle\Util\WorkflowProcessor
    arguments: ["@doctrine.orm.entity_manager"]
