<?php

namespace WorkflowBundle\Repository;

/**
 * NodeAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateWorkflowRepository extends \Doctrine\ORM\EntityRepository
{
}
